Document: zero-lliurex-jitsi
Title: Debian zero-lliurex-jitsi Manual
Author: <insert document author here>
Abstract: This manual describes what zero-lliurex-jitsi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zero-lliurex-jitsi/zero-lliurex-jitsi.sgml.gz

Format: postscript
Files: /usr/share/doc/zero-lliurex-jitsi/zero-lliurex-jitsi.ps.gz

Format: text
Files: /usr/share/doc/zero-lliurex-jitsi/zero-lliurex-jitsi.text.gz

Format: HTML
Index: /usr/share/doc/zero-lliurex-jitsi/html/index.html
Files: /usr/share/doc/zero-lliurex-jitsi/html/*.html
